# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5224f03aa2a4f8a8534743c780446d2fda5198ea89c2d197b3f704bc36bb56542b2b3c85c6d801074407cb41dd063dfed95f2de72ef38b3a3de3ab9e6e7e58e6

test:
  secret_key_base: 66996587974d26580e52ed760329d2ee4ff423a253f23692d3feba29c7889007cbae22a3b222f478e9a883a1c7c8d2422e0c7c50bc124584d114d0f68faddaf3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
